spring:
  data:
    mongodb:
      repositories:
        type: auto
      username: ${MONGODB_USERNAME:developer}
      password: ${MONGODB_PASSWORD:developer}
      host: ${MONGO:localhost}
      port: 27017
      authentication-database: admin
      database: test_async
